### PR TITLE
Fix #313; Decomposed Python notebook

### LINKED ISSUE #313: Decompose Python notebook into plain Python code modules

### PR DESCRIPTION
**Pull request by tilmankamp**

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
@tilmankamp Just a dumb question before I review, but how did you test this still works on multiple GPU's?

**Comment by tilmankamp** [comment]
@kdavis-mozilla Because it is mainly a `jupyter-nbconvert` code excerpt. However: I will also check this.

**Comment by kdavis-mozilla** [comment]
@tilmankamp Do you want to add in the latest merge from @reuben in to this PR?

**Comment by tilmankamp** [comment]
@kdavis-mozilla Yeah - I can do that. I'd manually apply his changes on top of this and force-push-overwrite current history to revert his merge.

**Comment by kdavis-mozilla** [comment]
Closing as @reuben landed a notebook decomposition

**Pull request closed without merging**
