### PR TITLE
Publish README/USING/TRAINING to readthedocs

### LINKED ISSUE #2581: Publish README/USING/TRAINING on readthedocs

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #2581

### CODE REVIEW

**Comment by lissyx** [comment]
@reuben https://ds-test.readthedocs.io/en/allthedocs/

Looks like we have broken links. Maybe splitting the doc into several files was not such a good idea. But now that we have ReadTheDocs, maybe we should keep a very light README, re-unite current `README.rst`, `USING.rst` and `TRAINING.rst` and direct people to full-blown ReadTheDocs page with extensive informations ?

**Comment by reuben** [comment]
Can you keep the split in the docs? Instead of using .include, actually package the files and link to them?

**Comment by lissyx** [comment]
> Can you keep the split in the docs? Instead of using .include, actually package the files and link to them?

I'm unsure what you mean here.

**Comment by reuben** [comment]
It seems like the links are broken because they link to the files, e.g. `USING.rst#blah-blah-section-name`. But in readthedocs all three files get embedded into a single one, `Basics.rst`, so the first part gets broken. If we keep they all separate the same way they are in the repo, then maybe the links will not be broken?

**Comment by lissyx** [comment]
> It seems like the links are broken because they link to the files, e.g. `USING.rst#blah-blah-section-name`. But in readthedocs all three files get embedded into a single one, `Basics.rst`, so the first part gets broken. If we keep they all separate the same way they are in the repo, then maybe the links will not be broken?

Yep. Is this way better and works for you ?

**Pull request merged**
