### PR TITLE
Provide an API function to free strings returned by API (Fixes #1979)

### LINKED ISSUE #1979: Provide a way to free strings allocated by deepspeech.cc in the API
Currently we return `malloc`'d strings and ask the user to `free` them, which can cause trouble if there's different allocators in the library and the application. We should provide an API function to free those strings.

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
The Java bindings use a completely different model, relying on SWIG cpointer and the Java code to manage memory rather than the bindings, and I don't know how to make sure they call appropriate free function when creating the Java String value. @lissyx any pointers?

**Comment by reuben** [comment]
Nevermind, newfree seems to work fine there as well.

**Comment by reuben** [comment]
External bindings will have to be updated but they are both still on 0.4.0.

**Comment by lissyx** [comment]
> External bindings will have to be updated but they are both still on 0.4.0.

I'm planning to send PR as part of https://github.com/mozilla/DeepSpeech/issues/2006

**Pull request merged**
