### PR TITLE
Force tables 3.4.4 because 3.5.1 does not provide python wheel

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
This is the reason behind the failures of python 3.4 training tests in #1960 : https://tools.taskcluster.net/groups/GUt2zSjTQi--ubC0xzx-sQ/tasks/bkNRfcZaRtmVGgEKqj5TXg/details cc @carlfm01

**Comment by lissyx** [comment]
@reuben asking upstream as well: https://github.com/PyTables/PyTables/issues/727

**Comment by reuben** [comment]
Given that it only fails on Python 3.4 (which reached end of life today), I'd suggest the alternative solution of dropping Python 3.4 support.

**Comment by lissyx** [comment]
@reuben EOL today, it was default python3 for debian jessie, and for ubuntu 14.04, maybe it's okay then.

**Pull request merged**
