### PR TITLE
Fix #314; Added environment variable for stride length

### LINKED ISSUE #314: Environment variable for time axis stride length

### PR DESCRIPTION
**Pull request by tilmankamp**

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
Looking at this makes me think I should wait on merging/reviewing this until the Fisher and Switchboard importers land, hopefully soon, because the changes here will have to be done there too, and it might be best to bundle them all in one big commit.

@tilmankamp What do you think?

**Comment by tilmankamp** [comment]
That was my reason for putting all this into a separate PR.

**Comment by kdavis-mozilla** [comment]
@tilmankamp I guess this is so out of date that it should addressed in another PR

**Comment by tilmankamp** [comment]
@kdavis-mozilla right

**Pull request closed without merging**
