### PR TITLE
Checking errors in USING.rst and TRAINING.rst

### PR DESCRIPTION
**Pull request by yuri20198**

### CODE REVIEW

**Comment by yuri20198** [comment]
> You can't force links to github like that this will break branches. `:github:` is here to take care of this. Can you explain why you do this?

':github:' didn't work for links.
And now it is working.

**Comment by reuben** [comment]
These files are meant to be rendered on deepspeech.readthedocs.io, where the links work fine. Here's an example:

https://deepspeech.readthedocs.io/en/v0.6.1/TRAINING.html#installing-python-dependencies

And the corresponding source:

https://github.com/mozilla/DeepSpeech/blob/v0.6.1/doc/TRAINING.rst#installing-python-dependencies

They don't render correctly on GitHub, but we couldn't find a way to make it work on both platforms. We should probably remove the links to the sub-files from the main README and just link to readthedocs to avoid this confusion.

**Comment by yuri20198** [comment]
> These files are meant to be rendered on deepspeech.readthedocs.io, where the links work fine. Here's an example:
> 
> https://deepspeech.readthedocs.io/en/v0.6.1/TRAINING.html#installing-python-dependencies
> 
> And the corresponding source:
> 
> https://github.com/mozilla/DeepSpeech/blob/v0.6.1/doc/TRAINING.rst#installing-python-dependencies
> 
> They don't render correctly on GitHub, but we couldn't find a way to make it work on both platforms. We should probably remove the links to the sub-files from the main README and just link to readthedocs to avoid this confusion.

I see a problem. This pull request was for document on GitHub

**Comment by reuben** [comment]
The ReadTheDocs contents are generated from the source on GitHub. The code to build it is here: https://github.com/mozilla/DeepSpeech/tree/master/doc

See the Makefile and conf.py. In particular, here is where the `github` scheme is set up: https://github.com/mozilla/DeepSpeech/blob/master/doc/conf.py#L199-L200

If you can find a way to make that work on both GitHub and ReadTheDocs, please send a PR. Otherwise, my plan is to remove references to the GitHub versions and link to ReadTheDocs instead.

**Pull request closed without merging**
