### PR TITLE
Fix csv writer parameter

### PR DESCRIPTION
**Pull request by ricky-cck**
https://docs.python.org/3/library/csv.html#csv.writer

### CODE REVIEW

**Comment by reuben** [comment]
Ugh, thanks for the PR. I don't even know why we're using `csv` here when we have `pandas` as a dependency already.

**Comment by reuben** [comment]
Hm, wait, `csvfile` is not a file object here. Have you actually observed incorrect behavior with the importer?

**Comment by ricky-cck** [comment]
script error in windows environment, adding this parameter will fix

**Comment by reuben** [comment]
OK, I see it now, I had misread the documentation before. We do pass a file-like to csv.DictWriter, and the file-like, not the writer, must be opened with `newline=''`. What a bad trap.

**Comment by reuben** [comment]
We have several other importers that also have this issue, could you also apply this fix to them?

```
rg -B 5 "csv\.DictWriter"
bin/import_cv2.py
127-
128-    output_csv = os.path.join(os.path.abspath(audio_dir), dataset + ".csv")
129-    print("Saving new DeepSpeech-formatted CSV file to: ", output_csv)
130-    with open(output_csv, "w", encoding="utf-8") as output_csv_file:
131-        print("Writing CSV file for DeepSpeech.py as: ", output_csv)
132:        writer = csv.DictWriter(output_csv_file, fieldnames=FIELDNAMES)

bin/import_slr57.py
160-    pool.join()
161-
162-    with open(target_csv_template.format("train"), "w") as train_csv_file:  # 80%
163-        with open(target_csv_template.format("dev"), "w") as dev_csv_file:  # 10%
164-            with open(target_csv_template.format("test"), "w") as test_csv_file:  # 10%
165:                train_writer = csv.DictWriter(train_csv_file, fieldnames=FIELDNAMES)
166-                train_writer.writeheader()
167:                dev_writer = csv.DictWriter(dev_csv_file, fieldnames=FIELDNAMES)
168-                dev_writer.writeheader()
169:                test_writer = csv.DictWriter(test_csv_file, fieldnames=FIELDNAMES)

bin/import_ts.py
132-    pool.join()
133-
134-    with open(target_csv_template.format("train"), "w") as train_csv_file:  # 80%
135-        with open(target_csv_template.format("dev"), "w") as dev_csv_file:  # 10%
136-            with open(target_csv_template.format("test"), "w") as test_csv_file:  # 10%
137:                train_writer = csv.DictWriter(train_csv_file, fieldnames=FIELDNAMES)
138-                train_writer.writeheader()
139:                dev_writer = csv.DictWriter(dev_csv_file, fieldnames=FIELDNAMES)
140-                dev_writer.writeheader()
141:                test_writer = csv.DictWriter(test_csv_file, fieldnames=FIELDNAMES)

bin/import_tuda.py
110-        csv_path = os.path.join(
111-            CLI_ARGS.base_dir, "tuda-{}-{}.csv".format(TUDA_VERSION, sub_set)
112-        )
113-        print('Writing "{}"...'.format(csv_path))
114-        with open(csv_path, "w") as csv_file:
115:            writer = csv.DictWriter(csv_file, fieldnames=FIELDNAMES)

bin/import_cv.py
126-    pool.close()
127-    pool.join()
128-
129-    print('Writing "%s"...' % target_csv)
130-    with open(target_csv, "w") as target_csv_file:
131:        writer = csv.DictWriter(target_csv_file, fieldnames=FIELDNAMES)

bin/import_swc.py
460-        set_samples = sorted(set_samples, key=lambda s: s.wav_path)
461-        base_dir = os.path.abspath(CLI_ARGS.base_dir)
462-        csv_path = os.path.join(base_dir, language + "-" + sub_set + ".csv")
463-        print('Writing "{}"...'.format(csv_path))
464-        with open(csv_path, "w") as csv_file:
465:            writer = csv.DictWriter(

bin/import_m-ailabs.py
138-    pool.join()
139-
140-    with open(target_csv_template.format("train"), "w") as train_csv_file:  # 80%
141-        with open(target_csv_template.format("dev"), "w") as dev_csv_file:  # 10%
142-            with open(target_csv_template.format("test"), "w") as test_csv_file:  # 10%
143:                train_writer = csv.DictWriter(train_csv_file, fieldnames=FIELDNAMES)
144-                train_writer.writeheader()
145:                dev_writer = csv.DictWriter(dev_csv_file, fieldnames=FIELDNAMES)
146-                dev_writer.writeheader()
147:                test_writer = csv.DictWriter(test_csv_file, fieldnames=FIELDNAMES)

bin/import_lingua_libre.py
137-    pool.join()
138-
139-    with open(target_csv_template.format("train"), "w") as train_csv_file:  # 80%
140-        with open(target_csv_template.format("dev"), "w") as dev_csv_file:  # 10%
141-            with open(target_csv_template.format("test"), "w") as test_csv_file:  # 10%
142:                train_writer = csv.DictWriter(train_csv_file, fieldnames=FIELDNAMES)
143-                train_writer.writeheader()
144:                dev_writer = csv.DictWriter(dev_csv_file, fieldnames=FIELDNAMES)
145-                dev_writer.writeheader()
146:                test_writer = csv.DictWriter(test_csv_file, fieldnames=FIELDNAMES)
```

**Comment by ricky-cck** [comment]
should I make another PR?

**Comment by reuben** [comment]
No, adding to this one is fine.

**Comment by reuben** [comment]
Thanks!

**Pull request merged**
