### PR TITLE
Bump version to v0.6.0

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
Is that actually used? I thought it was just included by accident, I guess I'm remembering incorrectly from our chat on IRC. The Makefile overwrites the file with the one from the root directory on build...

**Comment by lissyx** [comment]
Did we forgot to rename to README.rst?

**Comment by reuben** [comment]
> Shouldn't we also change all the examples/ deps to stick to v0.6.0 now ?

We can only do that after 0.6.0 is actually published, because otherwise the example task is going to fail.

**Comment by reuben** [comment]
Which means that someone browsing the v0.6.0 tag will see the example code pointing to alpha versions. But I don't know another way around that :/

**Comment by reuben** [comment]
The package does not use the checked in README.rst file: https://community-tc.services.mozilla.com/api/queue/v1/task/X2Pzmzu8RGGKezVR187ITw/runs/0/artifacts/public/deepspeech-0.6.0.tgz

**Comment by lissyx** [comment]
But we refer to it for doc, no?

**Comment by reuben** [comment]
Not that I can find.

**Comment by reuben** [comment]
Let's just unblock 0.6 and figure out the examples problem after that.

**Pull request merged**
