### PR TITLE
One more I/O Fix

### PR DESCRIPTION
**Pull request by CatalinVoss**
Fix one more F&R error with unpacking samples leftover from #3424

### CODE REVIEW

**Comment by CatalinVoss** [comment]
@reuben I'm a tad confused by the TaskCluster checks. Is there a general rule about which tests are supposed to pass/fail. A lot of the failures look unrelated and there may be some caching going on as well? The ones that look related are from this one extended training test: https://community-tc.services.mozilla.com/api/queue/v1/task/TdIY1v-XQZig0iRLGjT_OQ but when I try to reproduce that locally, all works fine now and I don't see the error:

```
python -u bin/import_ldc93s1.py ./data/smoke_test

python -u bin/data_set_tool.py ./data/smoke_test/ldc93s1.csv ./data/smoke_test/ldc93s1.sdb

python -u DeepSpeech.py --noshow_progressbar --noearly_stop --train_files ./data/smoke_test/ldc93s1.sdb --train_batch_size 1 --dev_files ./data/smoke_test/ldc93s1.sdb --dev_batch_size 1 --test_files ./data/smoke_test/ldc93s1.sdb --test_batch_size 1 --n_hidden 100 --epochs 220 --max_to_keep 1 --checkpoint_dir /tmp/ckpt_sdb --learning_rate 0.001 --dropout_rate 0.05 --export_dir /tmp/train_sdb --scorer_path data/smoke_test/pruned_lm.scorer --audio_sample_rate 8000

python -u DeepSpeech.py --noshow_progressbar --noearly_stop --train_files ./data/smoke_test/ldc93s1.sdb,./data/smoke_test/ldc93s1.csv --train_batch_size 1 --feature_cache /tmp/ldc93s1_cache_sdb_csv --dev_files ./data/smoke_test/ldc93s1.sdb,./data/smoke_test/ldc93s1.csv --dev_batch_size 1 --test_files ./data/smoke_test/ldc93s1.sdb,./data/smoke_test/ldc93s1.csv --test_batch_size 1 --n_hidden 100 --epochs 109 --max_to_keep 1 --checkpoint_dir /tmp/ckpt_sdb_csv --learning_rate 0.001 --dropout_rate 0.05 --export_dir /tmp/train_sdb_csv --scorer_path data/smoke_test/pruned_lm.scorer --audio_sample_rate 8000
```

Just want to make sure I leave things intact here!

**Comment by reuben** [comment]
They're all supposed to pass but there's something weird going on. I'll take a look.

**Comment by lissyx** [comment]
> They're all supposed to pass but there's something weird going on. I'll take a look.

It looks like TaskCluster changed something about how it deals with some artifacts uploads and we get gz-compressed when we should not

**Comment by lissyx** [comment]
I'm fixing in #3429 but on a tentative PR, it shows there are many regressions on training / inference for python since this has landed

**Comment by reuben** [comment]
After the PRs are done I'll back out the previously landed changes so the entire remote IO functionality can be merged as a single working PR.

**Comment by CatalinVoss** [comment]
Thanks to both of you! Ping me if you need me to do more cleanup here somewhere.

**Comment by reuben** [comment]
I've reverted the changes on master and pushed a new branch with all of your remote IO commits cherry picked onto it: https://github.com/mozilla/DeepSpeech/commits/reapply-remote-io

You should be able to start a PR from that branch and iterate on it to get tests green!

**Pull request closed without merging**
