### PR TITLE
Add a demos directory with two speech recognition demos

### PR DESCRIPTION
**Pull request by Cwiiis**

### CODE REVIEW

**Comment by Cwiiis** [comment]
Note, the VAD code still needs tweaking, but it's very situation/microphone-dependent. I think we can address this in follow-up.

**Comment by kdavis-mozilla** [comment]
How are we planning on serving the models? In other words on which computer will all of this run?

**Comment by Cwiiis** [comment]
Easiest to run the entire thing locally, but we could use an external server for serving the model if we prefer that for some reason. Note that the recording is done by the python binary, so the demos server can't be run externally.

**Comment by kdavis-mozilla** [comment]
As you're not at the all-hands, I want to make sure that someone knows enough to get this up and running and debug the inevitable problems that will arise.

**Comment by Cwiiis** [comment]
Makes sense - seeing as @andrenatal will be looking at it and has already built serving, I guess he makes sense? It's really not hard to get going though, it's all documented in the README included in this PR.

**Comment by kdavis-mozilla** [comment]
@andrenatal sounds good to me, just as long as someone is the designated driver.

**Comment by Cwiiis** [comment]
Does finding someone to run these demos in Hawaii block whether they should be accepted into the repository?

**Comment by kdavis-mozilla** [comment]
No. Just wanted to make sure someone is the point person for the server at Hawaii

**Comment by andrenatal** [comment]
Ok, I can do it.

**Pull request merged**
