### PR TITLE
Use ElementTree instead of deprecated cElementTree.

### LINKED ISSUE #3158: cElementTree has been deprecated and will be removed in favor of ElementTree
Reference : https://bugs.python.org/issue36543

```
bin/import_tuda.py
12:import xml.etree.cElementTree as ET

bin/import_swc.py
17:import xml.etree.cElementTree as ET
```

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:
- **Python version**: 3.8
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #3158

### CODE REVIEW

**Comment by lissyx** [comment]
@tirkarthi Have you ran the importers to make sure it is not breaking?

**Comment by tirkarthi** [comment]
ElementTree is a drop-in replacement of cElementTree. cElementTree exists only as an alias for ElementTree for compatibility reasons since Python 3.4+ provides C accelerated version by default. I tried running the script and it doesn't cause ImportError due to this PR though there are other import errors due to external dependencies since I have not installed deepsearch. I am getting below error on running `python setup.py install`

```
Processing dependencies for deepspeech-training==0.9.0a2
Searching for tensorflow==1.15.2
Reading https://pypi.org/simple/tensorflow/
No local packages or working download links found for tensorflow==1.15.2
error: Could not find suitable distribution for Requirement.parse('tensorflow==1.15.2')
```

**Comment by lissyx** [comment]
> No local packages or working download links found for tensorflow==1.15.2
> error: Could not find suitable distribution for Requirement.parse('tensorflow==1.15.2')

Looks like you are running on a too recent version of Python.

**Comment by lissyx** [comment]
> ElementTree is a drop-in replacement of cElementTree. cElementTree exists only as an alias for ElementTree for compatibility reasons since Python 3.4+ provides C accelerated version by default.

So it should be safe to merge, thanks!

**Comment by tirkarthi** [comment]
Thanks @lissyx. Just to add cElementTree.py is essentially just importing ElementTree

https://github.com/python/cpython/blob/master/Lib/xml/etree/cElementTree.py

```
# Deprecated alias for xml.etree.ElementTree

from xml.etree.ElementTree import *
```

**Pull request merged**
