### PR TITLE
Fixed #164

### LINKED ISSUE #164: Ability to limit data-set sizes also for non TED importers

### PR DESCRIPTION
**Pull request by kdavis-mozilla**

### CODE REVIEW

**Comment by tilmankamp** [comment]
What about ```ldc93s1```? The reason why I'm asking: If supported, we could have one call to ```read_data_sets``` that takes the limits from environment variables.

**Comment by kdavis-mozilla** [comment]
Good point.

I didn't add it as it will not have any effect for one file, but it's worth adding it to have all the API's look the same.

I'll do it.

**Comment by kdavis-mozilla** [comment]
@tilmankamp Could you look again

**Comment by tilmankamp** [comment]
LGTM

**Pull request merged**
