### PR TITLE
Add an importer for newsml formatted data

### PR DESCRIPTION
**Pull request by Cwiiis**
This adds an importer for newsml formatted data, specifically so we can import the data we've received from NPR. Given the format we've received it in, it requires that the SoX command-line client was built with mp3 support.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
@Cwiiis Could you explain the arguments to the command line a bit more?

Also, it failed when I ran it on metro_connection
```bash
(tf-warpctc-venv)doyouunderstand@ubuntu:~/Code/Cwiiis/DeepSpeech$ bin/import_newsml.py /data/NPR/WAMU/metro_connection /data/NPR/WAMU/metro_connection/raw
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Extracted 3 clips from m1100716
Extracted 200 clips from m1120504
Traceback (most recent call last):
  File "bin/import_newsml.py", line 152, in <module>
    _search_and_preprocess_data(sys.argv[1], sys.argv[2])
  File "bin/import_newsml.py", line 147, in _search_and_preprocess_data
    pandas.DataFrame(data=train, columns=columns).to_csv(os.path.join(data_dir, name + '_train.csv'), index=False)
  File "/home/doyouunderstand/tf-warpctc-venv/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1383, in to_csv
    formatter.save()
  File "/home/doyouunderstand/tf-warpctc-venv/local/lib/python2.7/site-packages/pandas/formats/format.py", line 1475, in save
    self._save()
  File "/home/doyouunderstand/tf-warpctc-venv/local/lib/python2.7/site-packages/pandas/formats/format.py", line 1576, in _save
    self._save_chunk(start_i, end_i)
  File "/home/doyouunderstand/tf-warpctc-venv/local/lib/python2.7/site-packages/pandas/formats/format.py", line 1602, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/lib.pyx", line 1171, in pandas.lib.write_csv_rows (pandas/lib.c:21083)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 3: ordinal not in range(128)
```

**Comment by kdavis-mozilla** [comment]
@Cwiiis It looks like with the changes I've added it will generally import most data sets. I've finished animal_house and metro_connection. The longer kojo_show and diane_rehm are still running.

**Comment by kdavis-mozilla** [comment]
Also some of the transcripts end up having value `None`, which should be checked for

**Comment by kdavis-mozilla** [comment]
Also looks like some of the wav's have size 0
```bash
...
[2017-06-05 23:17:27.533855] [worker 0] D Starting queue runners...
[2017-06-05 23:17:27.557206] [worker 0] D Queue runners started.
[2017-06-05 23:17:27.929717] [worker 0] Exception in thread Thread-15:
[2017-06-05 23:17:27.930242] [worker 0] Traceback (most recent call last):
[2017-06-05 23:17:27.930420] [worker 0]   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
[2017-06-05 23:17:27.930578] [worker 0]     self.run()
[2017-06-05 23:17:27.930732] [worker 0]   File "/usr/lib/python2.7/threading.py", line 763, in run
[2017-06-05 23:17:27.930874] [worker 0]     self.__target(*self.__args, **self.__kwargs)
[2017-06-05 23:17:27.931025] [worker 0]   File "/data/runs/kelly-npr/src/util/data_set_helpers.py", line 93, in _populate_batch_queue
[2017-06-05 23:17:27.931255] [worker 0]     source = audiofile_to_input_vector(wav_file, self._numcep, self._numcontext)
[2017-06-05 23:17:27.931450] [worker 0]   File "/data/runs/kelly-npr/src/util/audio.py", line 19, in audiofile_to_input_vector
[2017-06-05 23:17:27.931611] [worker 0]     orig_inputs = mfcc(audio, samplerate=fs, numcep=numcep)
[2017-06-05 23:17:27.931762] [worker 0]   File "/usr/local/lib/python2.7/dist-packages/python_speech_features/base.py", line 28, in mfcc
[2017-06-05 23:17:27.931922] [worker 0]     feat,energy = fbank(signal,samplerate,winlen,winstep,nfilt,nfft,lowfreq,highfreq,preemph,winfunc)
[2017-06-05 23:17:27.932089] [worker 0]   File "/usr/local/lib/python2.7/dist-packages/python_speech_features/base.py", line 54, in fbank
[2017-06-05 23:17:27.932240] [worker 0]     signal = sigproc.preemphasis(signal,preemph)
[2017-06-05 23:17:27.932436] [worker 0]   File "/usr/local/lib/python2.7/dist-packages/python_speech_features/sigproc.py", line 116, in preemphasis
[2017-06-05 23:17:27.932614] [worker 0]     return numpy.append(signal[0],signal[1:]-coeff*signal[:-1])
[2017-06-05 23:17:27.932790] [worker 0] IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by kdavis-mozilla** [comment]
For each "newml" data set we have its use of the newml format differs slightly. So, this code has to be adopted to each "newml" data set individually, something this PR does not do.

**Comment by Cwiiis** [comment]
Should this be closed or should these differences be investigated? Limited internet because I'm not in the country right now, but I'm tracking these bugs.

**Comment by kdavis-mozilla** [comment]
I'll take over, your on PTO.

I'm making N copies of the code then adopting the code to each of the N "newml" data sets.

**Comment by Cwiiis** [comment]
Are they all so different they need specific code? Newsml is a standard, it could be my handling of it is inadequate... Would be good not to duplicate so much code (and also not to leak too many details of data we can't share publicly).

**Comment by kdavis-mozilla** [comment]
> Are they all so different they need specific code?

Unfortunately yes

**Pull request closed without merging**
