### PR TITLE
Change TRIE format

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
```
$ time LD_LIBRARY_PATH=$(pwd)/../../tensorflow-lissyx/bazel-bin/native_client/ ./deepspeech --model ~/tmp/deepspeech-0.2/models/output_graph.pbmm --alphabet ~/tmp/deepspeech-0.2/models/alphabet.txt --lm ~/tmp/deepspeech-0.2/models/lm.binary --trie ~/tmp/deepspeech-0.2/models/trie --audio ~/tmp/deepspeech-0.2/audio/ -t 2>&1 | ts
oct. 01 17:41:41 TensorFlow: v1.11.0-5-g4cecc8c05b
oct. 01 17:41:41 DeepSpeech: v0.2.1-alpha.1-6-g72eaa2e
oct. 01 17:41:41 2018-10-01 17:41:41.946820: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
oct. 01 17:41:50 Running on directory /home/alexandre/tmp/deepspeech-0.2/audio/
oct. 01 17:41:50 > /home/alexandre/tmp/deepspeech-0.2/audio//2830-3980-0043.wav
oct. 01 17:41:50 experience proves this
oct. 01 17:41:50 cpu_time_overall=2.67239
oct. 01 17:41:50 > /home/alexandre/tmp/deepspeech-0.2/audio//4507-16021-0012.wav
oct. 01 17:41:50 why should one hall on the way'
oct. 01 17:41:50 cpu_time_overall=2.37770
oct. 01 17:41:50 > /home/alexandre/tmp/deepspeech-0.2/audio//8455-210777-0068.wav
oct. 01 17:41:50 your power is sufficient i saiy
oct. 01 17:41:50 cpu_time_overall=2.23482
real    0m8,405s
user    0m10,441s
sys     0m1,566s
```

**Comment by lissyx** [comment]
```
$ time LD_LIBRARY_PATH=$(pwd)/../../tensorflow-lissyx/bazel-bin/native_client/ ./deepspeech --model ~/tmp/deepspeech-0.2/models/output_graph.pbmm --alphabet ~/tmp/deepspeech-0.2/models/alphabet.txt --lm ~/tmp/
deepspeech-0.2/models/lm.binary --trie ../../LanguageModel/trie.trie --audio ~/tmp/deepspeech-0.2/audio/ -t 2>&1 | ts
oct. 01 17:42:37 TensorFlow: v1.11.0-5-g4cecc8c05b
oct. 01 17:42:37 DeepSpeech: v0.2.1-alpha.1-6-g72eaa2e
oct. 01 17:42:37 2018-10-01 17:42:37.550229: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
oct. 01 17:42:43 Running on directory /home/alexandre/tmp/deepspeech-0.2/audio/
oct. 01 17:42:43 > /home/alexandre/tmp/deepspeech-0.2/audio//2830-3980-0043.wav
oct. 01 17:42:43 experience proves this
oct. 01 17:42:43 cpu_time_overall=2.61065
oct. 01 17:42:43 > /home/alexandre/tmp/deepspeech-0.2/audio//4507-16021-0012.wav
oct. 01 17:42:43 why should one hall on the way'
oct. 01 17:42:43 cpu_time_overall=2.36580
oct. 01 17:42:43 > /home/alexandre/tmp/deepspeech-0.2/audio//8455-210777-0068.wav
oct. 01 17:42:43 your power is sufficient i saiy
oct. 01 17:42:43 cpu_time_overall=2.29402
real    0m5,597s
user    0m7,858s
sys     0m1,315s
```

**Comment by AtosNicoS** [comment]
I assume this change requires a rebuild of all models which will result in a new 2.1 release? Is it possible to test this somehow?

**Comment by lissyx** [comment]
@AtosNicoS We'll update with 0.2.1 but the rebuild just need to happen on the language model, and we document how to do that in `data/lm/README.md`, so you should be able to test it right now.

**Comment by lissyx** [comment]
@AtosNicoS Looks like I forgot to update `data/lm/trie` file, it should be fixed with https://github.com/mozilla/DeepSpeech/pull/1617

**Pull request merged**
