### PR TITLE
Fix positional arguments in README.md

### PR DESCRIPTION
**Pull request by nilakshdas**
The updated command has the positional arguments in the correct order to make inference work out of the box after getting the pre-trained model.

### CODE REVIEW

**Comment by lissyx** [comment]
Thanks for that @nilakshdas but we actually did change the order of arguments in #1211, so the documentation is already accurate :)

**Comment by lissyx** [comment]
@nilakshdas Correct me if I'm wrong, but the README in the v0.1.1 branch should be the proper one. Maybe we should improve our release processes to link to the proper README directly?

I don't think we link anything right now, and since this is the first "breaking" change, we are open to any suggestion :)

**Comment by nilakshdas** [comment]
You're right! The README in the v0.1.1 does have the correct ordering. But following the instructions from the master README, it explicitly states "the following command assumes you [downloaded the pre-trained model](https://github.com/mozilla/DeepSpeech#getting-the-pre-trained-model)." Following the link through, the download command wget's the v0.1.1 models which follows the old ordering and is the point where it all breaks. As a newcomer to this repo, this is not documented anywhere until you run `deepspeech -h` from the pip installed version (v0.1.1).

We can maybe add a line under the [**Getting the pre-trained model**](https://github.com/mozilla/DeepSpeech#getting-the-pre-trained-model) header with the correct ordering if one is getting the v0.1.1 models. If you're open to this idea, I can whip up a PR.

**Comment by luser** [comment]
I hit this same issue. I think it'd be worth a note in the README at least, just to avoid confusion until the new code winds up released on pypi.

**Comment by kdavis-mozilla** [comment]
@luser How would you phrase it and where in the READEME do you think it'd best be located?

**Pull request closed without merging**
