### PR TITLE
Fixed issue #2 and issue #4

### PR DESCRIPTION
**Pull request by kdavis-mozilla**
@andrenatal could you review this
@reuben this is the branch the [LibriVox](http://librivox.org/) loading code issue #47 and #46  should be based off of

### CODE REVIEW

**Comment by tilmankamp** [comment]
Some of this is already on master.

**Comment by kdavis-mozilla** [comment]
Yeah. Rebased, got conflicts and had to resolve them.

**Comment by andrenatal** [comment]
@kdavis-mozilla @tilmankamp Ok, I'm taking care of it.

**Comment by andrenatal** [comment]
@kdavis-mozilla I keep getting this error: `W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found. ` when training.

That might be happening because I'm not using Alex's Tensorflow with CTC?

**Comment by kdavis-mozilla** [comment]
@andrenatal `W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144`is a warning, check line 144 of the referred to file, it does not effect anything.

@andrenatal I don't think you are using the code from the branch `issue2`. If you look at the definition of `read_data_sets()` from the `issue2`branch[[1]](https://github.com/mozilla/DeepSpeech/blob/issue2/util/importers/ted_lium.py#L112) you see that in the branch `read_data_sets()` takes five arguments.

**Comment by kdavis-mozilla** [comment]
Merged with pull request #49

**Pull request closed without merging**
