### PR TITLE
Fix #284; BiRNN with stride 2

### LINKED ISSUE #284: Measure the WER increase vs comutation time decrease with a BiRNN stride of 2
Normally a RNN has time stride of `1` in time
```python
stride = 1
outputs = []
state = initial_state
with tf.variable_scope("RNN"):
  for time_step in range(0, num_steps, stride):
    if time_step > 0: tf.get_variable_scope().reuse_variables()
    (cell_output, state) = cell(inputs[:, time_step, :], state)
    outputs.append(cell_output)
```
However, a stride of `2` in time requires half the computation
```python
stride = 2
outputs = []
state = initial_state
with tf.variable_scope("RNN"):
  for time_step in range(0, num_steps, stride):
    if time_step > 0: tf.get_variable_scope().reuse_variables()
    (cell_output, state) = cell(inputs[:, time_step, :], state)
    outputs.append(cell_output)
```
Doing so with both RNN's of the BiRNN should cut computation by about a factor of two. However, it will also increase the WER.

The question to answer here is if this WER increase is worth the cut computation time.

### PR DESCRIPTION
**Pull request by tilmankamp**
Experimental PR - on ldc93s1 it reduced time by factor 2 AND converged faster (approximately 1.5 times - why?).
We now have to see how this performs on real/big data.

### CODE REVIEW

**Comment by reuben** [comment]
I think we need to run this on a larger corpus before drawing any conclusions. It's easier for a simpler network to overfit a smaller data set.

**Comment by kdavis-mozilla** [comment]
@tilmankamp Server's free, test away

**Comment by tilmankamp** [comment]
@kdavis-mozilla Should we already merge this?

**Comment by kdavis-mozilla** [comment]
For future reference, some benchmarking on this[[1](https://github.com/mozilla/DeepSpeech/issues/284#issuecomment-268496752)]

**Comment by kdavis-mozilla** [comment]
@tilmankamp I'm not sure.

Maybe we should merge then do a longer test over the long weekend?

I wanted to do a long test _not_ using warp-ctc to see if warp-ctc is causing our crashes.

Maybe we can combine the tests. _Not_ using warp-ctc and using stride two, as the concerns seem approximately orthogonal.

The only disadvantage I see is that we will not learn the effect on WER of _not_ using warp-ctc separate from that of using stride two.

**Comment by tilmankamp** [comment]
I'll add a parameter now...

**Pull request merged**
