### PR TITLE
Add UWP Nuget packing support

### LINKED ISSUE #2937: .NET Can not import DeepSpeech NuGet package
Hey there!

I want to use DeepSpeech in a .NET project and fortunately you already have a NuGet package available! But when I add DeepSpeech to my references by installing it in Visual Studio with the NuGet Manager, it is listed in my References but I can not import it with `using`. 

```C#
using DeepSpeechClient.Interfaces;
// The type or namespace name 'DeepSpeechClient' could not be found.
```

The .NET example project somehow works, but where is the difference?

Steps to reproduce:
- Create basic .NET CLI project in Visual Studio
- Add DeepSpeech with NuGet manager
- try import with `using DeepSpeechClient.Interfaces;`

Do you have any ideas? Am I missing something (I am new to windows stuff)?

### PR DESCRIPTION
**Pull request by carlfm01**
Fixes #2937

First attempt, I think the uwp build will fail let's see.

### CODE REVIEW

**Comment by lissyx** [comment]
@carlfm01 Gentle ping, do you need anything on our side to be able to move forward ?

**Comment by carlfm01** [comment]
@lissyx Ok, it failed, looks like the recommended deps missed to add: `c:\program files\dotnet\`  where should I set it? this cluster side or the cluster image definition side? And how? for Windows should be: `set PATH=%PATH%;c:\program files\dotnet\`

**Comment by lissyx** [comment]
You can overload `PATH` in the task definition, see win-opt-base.tyml

**Comment by lissyx** [comment]
@carlfm01 have you changed the github workers as i told you to do ? I dont see this change here.

**Comment by carlfm01** [comment]
Sure, @lissyx  what about adding another console example for uwp and run the test on it?

**Comment by lissyx** [comment]
You decide how its best done, im Just feeding ideas 😊

**Pull request merged**
