### PR TITLE
Update TensorFlow artifacts for rebuilding v0.1.1

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
All green, time to merge.

**Comment by ben-brown-or** [comment]
@lissyx Thanks for doing this. I'm assuming the builds are still going, so I'll wait for the artifacts to show up in TC. However, I don't see a retention policy on this build (or the corresponding tensorflow libs). Am I missing something? Is it infinite by default?

**Comment by 9define** [comment]
@lissyx Thanks for doing this. I'm assuming the builds are still going, so I'll wait for the artifacts to show up in TC. However, I don't see a retention policy on this build (or the corresponding tensorflow libs). Am I missing something? Is it infinite by default?

**Comment by lissyx** [comment]
The docs should already be accurate, please point where it is not.

**Comment by lissyx** [comment]
Once the pending PR I have is merged, it should be available again at the same place / link as before on TaskCluster. With a 6 months expiration. Once I'm back from PTO I'll take care if proper github release upload for long-term hosting. 

So expect if I'm mistaken and missing something there should be no problem for people requiring 0.1.1

**Comment by lissyx** [comment]
FTR, builds started: https://tools.taskcluster.net/groups/fuPyVwbxT4KGvBtWIzWcgA

**Comment by lissyx** [comment]
Woops, default behavior will publish them to "rebuild-0.1.1" of course. I've triggered some runs with proper v0.1.1 routes, so we should be safe.

**Comment by lissyx** [comment]
https://tools.taskcluster.net/groups/CgTzl5h0QAOZ5yxKWoTPpg
https://tools.taskcluster.net/groups/BNo2IXQtTpmiUHgiunxgbw
https://tools.taskcluster.net/groups/S32iTkLDTGm5wCbrtNTBiA
https://tools.taskcluster.net/groups/DxCYFU0kRJGDur6nzJToWA
https://tools.taskcluster.net/groups/R0rW_m5hQ-qDFKCevtF8Tw
https://tools.taskcluster.net/groups/Pqo4c0EvQ_KSxeo7R3yqSw
https://tools.taskcluster.net/groups/IxdvoGUcSAaRXUCFBL_hhQ

**Comment by 9define** [comment]
Thanks for all your work on this. If you get a chance to tag me on future PRs relating to long term hosting, please do so.

**Comment by lissyx** [comment]
First bits are coming through: https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.1.1/cpu

**Comment by lissyx** [comment]
@9define It will happen with your issue #1483, so you'll get pinged with update to that issue, don't worry :-)

**Pull request merged**
