### PR TITLE
add tensorflow submodule

### PR DESCRIPTION
**Pull request by imskr**
- Part of #2895

### CODE REVIEW

**Comment by imskr** [comment]
@lissyx Please review this

**Comment by imskr** [comment]
@lissyx Why 3 tests fails on TC?

**Comment by reuben** [comment]
@imskr you can check the logs for yourself, just click on the failed task and then click "View Live Logs".

**Comment by reuben** [comment]
In this case the failures look like they're network related, some intermittent connection failure. You can rerun the task by clicking on it and then using the action button on the bottom right corner.

**Comment by imskr** [comment]
cool, thanks @reuben

**Comment by reuben** [comment]
You should be able to do it if you login with GitHub, as you have contributor access to this repo. In any case, there's no point in rerunning these tasks, as this PR hasn't changed any code, so it also won't change any tests.

**Comment by reuben** [comment]
Ah, no, I guess you can't, it's still hardcoded to specific people and teams.

**Comment by imskr** [comment]
@reuben @lissyx Can you test this?

**Comment by reuben** [comment]
@imskr there's nothing here to be tested. The goal of this issue is to change the build scripts, documentation, tests, etc to work with a submodule instead of separate repos. Creating the submodule is just the first step.

**Comment by imskr** [comment]
Okay so I've created the submodule. Now what should I do next?

**Comment by reuben** [comment]
Follow the build documentation but with the paths adapted to use the submodule instead of a separate repo, see what breaks, try to fix it, report here if you get stuck.

**Comment by lissyx** [comment]
@imskr Are you still trying to work on that ?

**Comment by imskr** [comment]
@lissyx I'm going to do it today

**Comment by imskr** [comment]
@lissyx I'm closing this. Sorry, got stuck in other work and you have a PR for this.

**Pull request closed without merging**
