### PR TITLE
Replace structs with IntPtr .NET

### PR DESCRIPTION
**Pull request by carlfm01**
We no longer need ModelState and StreamingState structs mapping to the managed side. 

While testing the change I've noticed a memory leak happens creating and destroying the model with LM enabled, without LM enabled works fine, with about 20 runs of creating and destroying the model the memory usage went from 200MB to 700MB, @lissyx @reuben any thoughts?

The same happened with the Structs so it's not related to this change, sending the PR.

### CODE REVIEW

**Comment by lissyx** [comment]
For the leak, can you file an issue? If you can check where it comes from and/or if it reproduces under Linux it'd be awesome 😁

**Comment by lissyx** [comment]
I'll let @reuben review as well

**Comment by lissyx** [comment]
> without LM enabled works fine, with about 20 runs of creating and destroying the model the memory usage went from 200MB to 700MB, @lissyx @reuben any thoughts?

Can you check if it could be a regression on Windows due to #2384 ?

**Comment by carlfm01** [comment]
> If you can check where it comes from and/or if it reproduces under Linux it'd be awesome

Yes, let me get back to my VM tomorrow.



> Can you check if it could be a regression on Windows due to #2384 ?

@lissyx yes, I'll check if it is related, I'll test the previous version to that change and report back.

**Pull request merged**
