### PR TITLE
Merge wer

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
@kdavis-mozilla I guess you want to review this to make sure the branch makes sense.

**Comment by kdavis-mozilla** [comment]
@lissyx Maybe wait on the work @reuben is doing on issue #340 ?

**Comment by lissyx** [comment]
Up to you :)

**Comment by lissyx** [comment]
I could complete a whole automation execution, nothing written to $HOME/.local/share and all in /data/deepspeech_wer :)

Let's close, this will get merged with issue #340.

**Pull request closed without merging**
