### PR TITLE
adding instructions on how to set git-lfs

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**
adding instructions on how to set git-lfs

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
@tiagmoraismorgado Thanks for the PR.

One question I have, before going into a formal review is: Should this project be in the business of maintaining the details of git lfs setup or should we defer to the git lfs website. I just worry that putting this info here will lead to it being out of date quickly.

**Comment by tiagmoraismorgado** [comment]
@kdavis-mozill**a i just felt like there should be more detailed instructions on the repository in order to:**

- _explain how users can actually get git-lfs to run properly_

**the motivation behind that is:**
- _the fact that this is a key element in the process of getting deepspeech to run._ 

**for instance:**
- _i first looked into brew install git-lfs_
- _i didn't link the repository, and it was an important thing to get it running_

**the i came with an issue, on how to get git-lfs to run:**
- _you pointed me that i had to install git-lfs_
- _i didn't know that i had to link it_
- _i didn't know that i had to initialize it_

**as soon as i initialized it:**
- _i was able to get the training to be done;_
- _the console printed up a malfunction output;_
- _but then it worked out._

**i think it is important to give users insight on how they can get git-lfs to run on their own plattform, so that they can get it to run properly**

**Comment by tiagmoraismorgado** [comment]
**_and more important, doing it for all plattforms_**

**Comment by lissyx** [comment]
There should be no extra step if you git clone after you installed git-lfs and it is properly installed and accessible in the PATH.

**Comment by tiagmoraismorgado** [comment]
ok, feel free to close this PR, if you feel like doing so 👍

**Comment by tilmankamp** [comment]
@lissyx At least for MacOS I tried to clone after installation and it was not working before I did an extra `git lfs install` and then the clone.
@tiagmoraismorgado Your instructions are for MacOS only. Could you also add instructions for Linux?

**Comment by tiagmoraismorgado** [comment]
yes, but i have to search for the proper mean of doing so

**Comment by kdavis-mozilla** [comment]
@tiagmoraismorgado I'm going to close this PR.

**Pull request closed without merging**
