### PR TITLE
Bump version to v0.6.1-alpha.0

### PR DESCRIPTION
**Pull request by reuben**
Testing the new TFLite packages on desktop.

### CODE REVIEW

**Comment by reuben** [comment]
Getting some weird infra failures in the Pixel tests, seems unrelated to the code:

emulator: INFO: QtLogger.cpp:68: Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by reuben** [comment]
Hm, they actually go back at least a week, so we're missing test coverage there.

It fails before tests are run, during `android_setup_emulator`:

```
+ ./tools/emulator -verbose -avd ds-pixel -no-skin -no-audio -no-window -no-boot-anim -accel off
+ adb wait-for-device
emulator:Android emulator version 26.0.3.0 (build_id 3965150)
emulator:Found AVD name 'ds-pixel'
emulator:Found AVD target architecture: arm
emulator:argv[0]: './tools/emulator'; program directory: '/home/build-user/DeepSpeech/Android/SDK/tools'
emulator:  Found directory: /home/build-user/DeepSpeech/Android/SDK/system-images/android-24/google_apis/armeabi-v7a/

emulator:Probing for /home/build-user/DeepSpeech/Android/SDK/system-images/android-24/google_apis/armeabi-v7a//kernel-ranchu: file exists
emulator:Auto-config: -engine qemu2 (based on configuration)
emulator:  Found directory: /home/build-user/DeepSpeech/Android/SDK/system-images/android-24/google_apis/armeabi-v7a/

emulator:try dir /home/build-user/DeepSpeech/Android/SDK/tools
emulator:try dir ./tools/
emulator:try dir ./emulator
emulator:Found target-specific 64-bit emulator binary: /home/build-user/DeepSpeech/Android/SDK/./emulator/qemu/linux-x86_64/qemu-system-armel
emulator:Adding library search path: './emulator/lib64'
emulator:Adding library search path: './emulator/lib64/gles_swiftshader'
emulator:Adding library search path: './emulator/lib64/gles_angle'
emulator:Adding library search path: './emulator/lib64/gles_angle9'
emulator:Adding library search path: './emulator/lib64/gles_angle11'
emulator:Adding library search path: './emulator/lib64/libstdc++'
emulator: Adding library search path for Qt: './emulator/lib64/qt/lib'
emulator: Setting Qt plugin search path: QT_QPA_PLATFORM_PLUGIN_PATH=./emulator/lib64/qt/plugins
emulator: Running :/home/build-user/DeepSpeech/Android/SDK/./emulator/qemu/linux-x86_64/qemu-system-armel
emulator: qemu backend: argv[00] = "/home/build-user/DeepSpeech/Android/SDK/./emulator/qemu/linux-x86_64/qemu-system-armel"
emulator: qemu backend: argv[01] = "-verbose"
emulator: qemu backend: argv[02] = "-avd"
emulator: qemu backend: argv[03] = "ds-pixel"
emulator: qemu backend: argv[04] = "-no-skin"
emulator: qemu backend: argv[05] = "-no-audio"
emulator: qemu backend: argv[06] = "-no-window"
emulator: qemu backend: argv[07] = "-no-boot-anim"
emulator: qemu backend: argv[08] = "-accel"
emulator: qemu backend: argv[09] = "off"
emulator: Concatenated backend parameters:
 /home/build-user/DeepSpeech/Android/SDK/./emulator/qemu/linux-x86_64/qemu-system-armel -verbose -avd ds-pixel -no-skin -no-audio -no-window -no-boot-anim -accel off
* daemon not running; starting now at tcp:5037
emulator: WARNING: the -no-skin flag is obsolete. to have a non-skinned virtual device, create one through the AVD manager
emulator: autoconfig: -skin 1080x1920
emulator: autoconfig: -skindir (null)
emulator: autoconfig: -kernel /home/build-user/DeepSpeech/Android/SDK/./system-images/android-24/google_apis/armeabi-v7a//kernel-ranchu
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /home/build-user/DeepSpeech/Android/SDK/./system-images/android-24/google_apis/armeabi-v7a//ramdisk.img
emulator: Using initial system image: /home/build-user/DeepSpeech/Android/SDK/./system-images/android-24/google_apis/armeabi-v7a//system.img
emulator: No vendor image
emulator: autoconfig: -initdata /home/build-user/DeepSpeech/Android/SDK/.android/avd/ds-pixel.avd/userdata.img
emulator: autoconfig: -cache /home/build-user/DeepSpeech/Android/SDK/.android/avd/ds-pixel.avd/cache.img
emulator: Increasing RAM size to 1024MB
emulator: VM heap size 0MB is below hardware specified minimum of 256MB,setting it to that value
emulator: System image is read only
emulator: Found 1 DNS servers: 169.254.169.254
emulator: found magic skin width=1080 height=1920 bpp=16

statvfs('/home/build-user/DeepSpeech/Android/SDK/.android/avd/ds-pixel.avd/snapshots/default_boot/ram.img') failed: No such file or directory
emulator: Creating ext4 userdata partition: /home/build-user/DeepSpeech/Android/SDK/.android/avd/ds-pixel.avd/data
emulator: cannot read adb key file: /home/build-user/DeepSpeech/Android/SDK/.android/adbkey.pub
emulator: trying again by copying from home dir
emulator: cannot read adb key file: /home/build-user/DeepSpeech/Android/SDK/.android/adbkey
emulator: trying again by copying from home dir
Creating filesystem with parameters:
    Size: 838860800
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7328
    Inode size: 256
    Journal blocks: 3200
    Label: 
    Blocks: 204800
    Block groups: 7
    Reserved block group size: 55
Created filesystem with 60/51296 inodes and 10727/204800 blocks
emulator: WARNING: encryption is off
emulator: Creating empty ext4 cache partition: /home/build-user/DeepSpeech/Android/SDK/.android/avd/ds-pixel.avd/cache.img
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
emulator: INFO: QtLogger.cpp:68: Warning: could not connect to display  ((null):0, (null))


emulator: INFO: QtLogger.cpp:68: Info: Could not load the Qt platform plugin "xcb" in "./emulator/lib64/qt/plugins" even though it was found. ((null):0, (null))


Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
emulator: INFO: QtLogger.cpp:68: Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))


* daemon started successfully

[taskcluster:error] Task timeout after 3600 seconds. Force killing container.
```

**Comment by reuben** [comment]
Tried a bunch of workarounds but nothing seems to work. Maybe there was an update to the Android tooling that broke this recently?

**Comment by reuben** [comment]
@lissyx have you seen this failure before?

**Comment by lissyx** [comment]
> @lissyx have you seen this failure before?

No, but I'm wondering if it would not be just because of some missing system-level dependencies. Do you have a full log ? We should have a fake X server running for the emulator to connect to, this error suggests that Qt-code is unable to connect to X.

**Comment by reuben** [comment]
Full log doesn't offer much help, nothing about a X server in it: https://community.taskcluster-artifacts.net/a5vQm0D2RXqzx2CqOVe9wA/0/public/logs/live_backing.log

**Pull request merged**
