### PR TITLE
Add option for output file

### PR DESCRIPTION
**Pull request by stellarpower**

### CODE REVIEW

**Comment by lissyx** [comment]
@stellarpower Thanks, but I think you did a mistake opening a PR against this repo instead of your fork.

**Comment by stellarpower** [comment]
Hi, don't think I made a mistake, I had downloaded this file to run deepspeech on my machine and wanted to output the results without the extra information on stdout cluttering this, so thought it might be useful to add a switch and just used the browser-based editor to submit the changes.

**Comment by lissyx** [comment]
You can use your shell redirect.

**Comment by stellarpower** [comment]
I can, this just seemed neater for the situation in which I was using it at least, and I thought I might as well push that back as it's only a small feature. The help message doesn't make it fully clear either what is happening with the results of the inference; something like ''--output file   File to write text result (default is stdout)" would clarify this.

**Pull request closed without merging**
