### PR TITLE
Specify upper frequency limit when computing Mfccs

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by lissyx** [comment]
As said on IRC, on french model I could see a ~5% increase in quality, i.e., ~5% decrease in WER, compared to previous training, using the same parameters.

**Comment by kdavis-mozilla** [comment]
The 5% coincides with the result presented [here](https://www.dpamicrophones.com/mic-university/facts-about-speech-intelligibility) for non-tonal languages
facts-about-speech-fig04_1
I'd guess we'd gain more for tonal languages.

**Comment by lissyx** [comment]
> The 5% coincides with the result presented [here](https://www.dpamicrophones.com/mic-university/facts-about-speech-intelligibility) for non-tonal languages
> facts-about-speech-fig04_1
> I'd guess we'd gain more for tonal languages.

That would mean we can safely land that and pick the improvement over the next round of training, without fearing of hyper-parameters changes, then?

**Comment by kdavis-mozilla** [comment]
It might mean that. At least this coincides with your initial experiences and these numbers.

**Pull request merged**
