### PR TITLE
Fix #253; Set state_is_tuple=True on BasicLSTMCell

### LINKED ISSUE #253: Set state_is_tuple=True on BasicLSTMCell
It is said to have a performance impact to keep the cell's state as tuple. We need to test this. Please be aware that this most probably implies a change to the model's structure.

### PR DESCRIPTION
**Pull request by tilmankamp**
Experimental PR - to be checked on a big machine. Be warned: Most probably this changes the graph.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
I'm going to wait on the review until we get a chance to test on the large machine.

**Comment by kdavis-mozilla** [comment]
@tilmankamp Could you test this tomorrow, after the PSU gets installed?

**Comment by tilmankamp** [comment]
@kdavis-mozilla Yeah - I will try to get a performance comparison.

**Comment by tilmankamp** [comment]
I did some simple test with 2000 TED training samples in one epoch. Here are the results:
```
master:
FINISHED Epoch 0000   Overall epoch time: 0:01:13   Training time: 0:01:09
issue253 rebased onto same master:
FINISHED Epoch 0000   Overall epoch time: 0:01:12   Training time: 0:01:08
```
This is within error margin. The setting seems to have NO significant effect.

**Comment by tilmankamp** [comment]
Closing it.

**Comment by reuben** [comment]
Don't we wanna set this anyway, since it's deprecated and unsupported in
future tensorflow versions?

**Comment by tilmankamp** [comment]
@reuben It's a valid point, but it'd change the graph.
@kdavis-mozilla What do you vote for?

**Comment by kdavis-mozilla** [comment]
@tilmankamp @reuben I'd guess we should switch to `state_is_tuple=True` just to stay ahead of deprecation.

**Pull request merged**
