### PR TITLE
Allow limiting epoch size

### PR DESCRIPTION
**Pull request by Cwiiis**
Limiting the epoch size allows for more incremental progress reporting.

### CODE REVIEW

**Comment by Cwiiis** [comment]
Don't worry about this until tilman lands his patch, just want to stick it up. I think using this as a foundation for the weighted smaller samples we spoke about makes sense.

**Comment by Cwiiis** [comment]
This patch just allows for more incremental progress reporting - as such, possibly not desirable. Feel free to close, I'll come back with the weighting patch that's more interesting :)

**Comment by kdavis-mozilla** [comment]
Ok got it!

**Comment by kdavis-mozilla** [comment]
Doing some clean up. I'll take you up on the offer to close this.

**Pull request closed without merging**
