### PR TITLE
Simplified getting started

### PR DESCRIPTION
**Pull request by pannous**
added requirements.txt and better Readme

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
Thanks for the PR. I'll take on the review.

**Comment by reuben** [comment]
There's a [requirements.txt in doc/](https://github.com/mozilla/DeepSpeech/blob/master/doc/requirements.txt) already that is used for building the docs. We can move it to the root of the tree and then I can change the setting on readthedocs.org to avoid redundancy, if you'd prefer.

**Comment by kdavis-mozilla** [comment]
Why did you close the PR?

**Comment by pannous** [comment]
creating a clean one with just improved README.md

**Comment by kdavis-mozilla** [comment]
OK. Just make another PR when you're ready and I'll review it.

**Pull request closed without merging**
