### PR TITLE
WIP: ArchLinux PKGBUILD

### PR DESCRIPTION
**Pull request by lissyx**
Tentive fix for issue #979

### CODE REVIEW

**Comment by lissyx** [comment]
@AtosNicoS No, I have not retried. What error are you facing ?

**Comment by lissyx** [comment]
@AtosNicoS For me it's failing because of wheel: we need a newer version, and since there is no virtualenv being setup (no idea how to do that properly in the PKGBUILD), then it's trying to change the system's one.

**Comment by lissyx** [comment]
@AtosNicoS With venv in the pkguild, it's green now

**Comment by NicoHood** [comment]
For reference here is the error:
```
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/Half.h:80:8: note: 'Eigen::TensorMap<Eigen::Tensor<Eigen::half, 2, 1, long int>, 16, Eigen::MakePointer>::Scalar' {aka 'struct Eigen::half'} declared here
 struct half : public half_impl::half_base {
        ^~~~
INFO: From Compiling native_client/kenlm/lm/vocab.cc:
native_client/kenlm/lm/vocab.cc:285:43: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void MissingUnknown(const Config &config) throw(SpecialWordMissingException) {
                                           ^~~~~
native_client/kenlm/lm/vocab.cc:297:67: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 void MissingSentenceMarker(const Config &config, const char *str) throw(SpecialWordMissingException) {
                                                                   ^~~~~
INFO: From Compiling native_client/generate_trie.cpp:
In file included from native_client/generate_trie.cpp:7:
native_client/trie_node.h:29:28: warning: multi-character character constant [-Wmultichar]
   static const int MAGIC = 'TRIE';
                            ^~~~~~
INFO: From Compiling tensorflow/core/kernels/maxpooling_op.cc:
In file included from ./tensorflow/core/platform/types.h:38,
                 from ./tensorflow/core/framework/numeric_types.h:28,
                 from ./tensorflow/core/kernels/maxpooling_op.h:20,
                 from tensorflow/core/kernels/maxpooling_op.cc:20:
./tensorflow/core/lib/bfloat16/bfloat16.h: In member function 'tensorflow::bfloat16::operator float() const':
./tensorflow/core/lib/bfloat16/bfloat16.h:99:12: warning: 'result' is used uninitialized in this function [-Wuninitialized]
     return result;
            ^~~~~~
INFO: Elapsed time: 903.373s, Critical Path: 136.78s
INFO: 918 processes: 918 local.
INFO: Build completed successfully, 931 total actions
INFO: Build completed successfully, 931 total actions
c++ -o deepspeech   `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/build/deepspeech/src/tensorflow/bazel-bin/native_client  -ldeepspeech -ldeepspeech_utils  `pkg-config --libs sox`
pip install --quiet numpy wheel==0.31.0 setuptools==39.1.0
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/bin/wheel'
Consider using the `--user` option or check the permissions.

make: *** [Makefile:34: bindings-build] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /var/lib/archbuild/extra-x86_64/arch/build
```

The fix MUST be in the PKGBUILD, otherwise it cannot be built reproducible.

I do not know where I posted a fix for the makefile but I remember that I made come changes to not generate any wheel package at all. I cannot find those again. Currently we package it as wheel and then extract it again. We could package it as normal python install directly, no need to setup an venv. Do you remember where I posted those improvements?

**Comment by lissyx** [comment]
Ok, so you have the same error. I remember your requirement, but I don't know what happened to your change, sorry :/

**Comment by lissyx** [comment]
@AtosNicoS Maybe you could just use the `bindings-build` make target, and then copy the files?

**Comment by lissyx** [comment]
@AtosNicoS We don't have a planning with dates for 0.2.0. It should happen soon. You can already test with the alpha tags ...

Make a PR, we should be able to include that

**Pull request closed without merging**
