### PR TITLE
Update import_cv2.py

### PR DESCRIPTION
**Pull request by Murcurio**
Requires utf8 encoding, without this it tries to read it as ascii and fails

### CODE REVIEW

**Comment by lissyx** [comment]
@Murcurio We have had no issue with UTF-8, this is likely your system ?

**Comment by Murcurio** [comment]
I've had the same issue on Ubuntu, redhat and with the Dockerfile. Could be
an issue with the latest CV dataset perhaps.

**Comment by lissyx** [comment]
> I've had the same issue on Ubuntu, redhat and with the Dockerfile. Could be an issue with the latest CV dataset perhaps.

We had no issue with the latest Common Voice dataset. How are you running things ?

**Comment by Tortoise17** [comment]
For me, 
# -*- coding: utf-8 -*-
this in the start helped.

**Pull request merged**
