### PR TITLE
Allow for different sample rate exports

### PR DESCRIPTION
**Pull request by rhamnett**
Sets output format to Sox transformer

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
A possibly dumb question, but why allow for the sample rate to be changed when currently the rest of the pipeline doesn't allow for such, and why just this importer?

**Comment by rhamnett** [comment]
The sample rate needs to be changed all over the place but this at least collects it into one place for each of these files rather than having to go back in everywhere when each version is released, it will merge better.

**Comment by kdavis-mozilla** [comment]
Got, it. So the will be over N PR's where N is much greater than 1 :)

**Comment by rhamnett** [comment]
Haha, I get you :) I will try and do some work to more easily cater for sample rates across the different files in a single PR if you wish? Any suggestions welcome before I start

**Comment by bernardohenz** [comment]
@rhamnett you can run a search over all files for "16000" and make this dynamic. I believe you can make these variables dependable from the `sample_rate` saved in the model's metadata (exported [here](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L719))

**Pull request merged**
