### PR TITLE
Use simple README pointing to GitHub for JS/Python packages

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
NuGet doesn't show any inline listing. I looked for a README being included from the Java bindings but couldn't find it. I'll file a follow up anyway.

**Comment by lissyx** [comment]
@reuben Are we properly packaging it for NPM repository? https://www.npmjs.com/package/deepspeech it shows `"Unable to find a readme for deepspeech@0.6.0"`

**Comment by reuben** [comment]
Hm. It regressed in 0.6.0-alpha.9...

**Comment by reuben** [comment]
Ah, that's when we switched from Markdown to RST. https://github.com/mozilla/DeepSpeech/compare/v0.6.0-alpha.8...v0.6.0-alpha.9#diff-adbf4c5414aca84d7c8d4a094f6575b0

**Pull request merged**
