### PR TITLE
build ctcdecode on ppc64le

### PR DESCRIPTION
**Pull request by NanoNabla**
Solves #3379
- Makes building ctcdecode on PowerPC `ppc64le` and other non x86/arm systems with linux possible
- set `PYTHON_PLATFORM_NAME` and `SWIG_DIST_URL` in environment
- For `ppc64le` set `PYTHON_PLATFORM_NAME="--plat-name linux_ppc64le"`.  This should be mentioned somehow in docu
- It should also be mentioned to use https://github.com/lissyx/swig/tree/taskcluster instead of plain swig

### CODE REVIEW

**Comment by lissyx** [comment]
> For `ppc64le` set `PYTHON_PLATFORM_NAME="--plat-name linux_ppc64le"`. This should be mentioned somehow in docu

I'm not sure how we can document that in a way that does not get messy

**Review by lissyx — APPROVED** [review]

**Comment by lissyx** [comment]
@NanoNabla Let's see if it's green with that, and thanks!

**Comment by NanoNabla** [comment]
> I'm not sure how we can document that in a way that does not get messy
I think at a minimum somehow in a discourse thread. Since ppc64le is used on IBM's AC922 their should be some user which are targeted.

**Comment by NanoNabla** [comment]
I nearly forgot:
It should also be mentioned to use https://github.com/lissyx/swig/tree/taskcluster instead of plain swig when there are no prebuilds. I did not found this in the docu.

**Comment by lissyx** [comment]
There are some failures, but it's unrelated. Thanks @NanoNabla

**Comment by lissyx** [comment]
>  It should also be mentioned to use https://github.com/lissyx/swig/tree/taskcluster instead of plain swig when there are no prebuilds. I did not found this in the docu.

I remember  I documented that in the past. Please make a new PR against `doc/` to make sure we cover this.

Maybe introduce some "Building CTC Decoder for training on unsupported platforms" ?

**Pull request merged**
