### PR TITLE
Bug fix - test_csvs argument was ignored

### PR DESCRIPTION
**Pull request by Jendker**
Removed spurious overwriting of argument 'test_csvs' in evaluate.py
This bug lead to problems in lm_optimizer.py

### CODE REVIEW

**Comment by Jendker** [comment]
The variable is used on the next line, that's fine.

But the function argument has the same variable name and is overwritten.
This leads to problems in lm_optimizer.py where each time all test_csvs are used, because given argument is ignored.

**Comment by kdavis-mozilla** [comment]
Have you checked all other calls to evaluate() to make sure they don't rely on this overwriting?

**Comment by Jendker** [comment]
Yes, I've checked it. Everywhere else as argument `FLAGS.test_files.split(',')` was given, so the bug was hidden. Other case is only in lm_optimizer.py, where this fix corrects the pruner behaviour.

**Comment by kdavis-mozilla** [comment]
Hmm.

Looks like the only other calls are train.py:643, evaluate.py:143, and lm_optimizer.py:36. All of those look like they don't rely on the overwriting and the only one which breaks as a result of the overwriting is lm_optimizer.py:36.

So you're change looks good.

**Comment by kdavis-mozilla** [comment]
Thanks!

**Pull request merged**
