### PR TITLE
Added support for inter-op and intra-op parallelism threads.

### PR DESCRIPTION
**Pull request by bhavani-subramanian**
Setting these parameters would boost CPU performance (https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture). More information about these parameters can be found here: https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/core/protobuf/config.proto

### CODE REVIEW

**Comment by lissyx** [comment]
Please also note that this article specifically target some Intel specific mkl-dnn that we don't play with.

**Comment by bhavani-subramanian** [comment]
https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/core/common_runtime/process_util.cc#L58 shows how the default values of inter/intra-op threads are being set if nothing is specified.

Consider a scenario where there is a 2 socket SKX machine with 28 cores/socket. If the user wants to run inference on only a single socket, they can run the following command:
```
numactl --physcpubind=0-27 --membind=0 taskset -c 0-27 python -u DeepSpeech.py \
--log_level 1 \
--checkpoint_dir "$ckpt_dir" \
--one_shot_infer "$audiofile_path/$audiofile_name" \
--inter_op 1 \
--intra_op 28 \
```
Now, if inter and intra-op flags are not passed, it can easily lead to over-subscription of threads since the default behavior is to utilize all available physical cores. These flags provide a way for the user to override the default settings.

**Comment by lissyx** [comment]
Thanks. That link points to ifdef on Intel mkl, is this what you meant?

Now, we don't build our inference lib with mkl, so I'm unsure of the impact. From my reading of the documentation of MKL it was clear there was only a win regarding training, and not inference. 

Also, relying on deepspeech.py for inference is not the default path. Could this have any value any other place, or during GPU training? 

The changes themselves are good and very limited, so I'd be not against it, I'm just worrying about another set of parameters we need to support and the specific behavior it might have.

I'll defer the final decision, though, to @reuben or @kdavis-mozilla.

**Comment by kdavis-mozilla** [comment]
Ditto

**Comment by bhavani-subramanian** [comment]
Thanks @lissyx. The link shows how intra/inter-op flags are being set when TF is built with and without MKL. As I mentioned earlier, the default behavior (i.e. when these flags are not passed by the user) when building with MKL is to utilize all available physical cores, which may not be desirable when the user needs to utilize specific cores in the system.

AFAIK, these flags are useful only when running on CPUs (both inference and training) and have no effect when running on GPUs.

Do let me know if you have further questions.

**Comment by reuben** [comment]
I don't know if it's just GitHub messing up the UI here, but it's showing me a huge changeset. I committed directly in f7fef57e64875ba3e160382e4cb0de35a735227d. Thanks for the PR!

**Pull request closed without merging**
