### PR TITLE
Add mandarin tools in bin/ for converting transcript and generating alphabet file

### PR DESCRIPTION
**Pull request by mychiux413**
Hi,
Due to the number of mandarin characters are unknowable, so I wrote 2 tools to easily deal with mandarin dataset:

* add `bin/convert_csv_zh_cn_to_zh_tw.py` for converting transcript between `zh-tw` <-> `zh-cn`
  - basic usage `python bin/convert_csv_zh_cn_to_zh_tw.py --from_file <from_csv> --to_file <to_csv>`
* add `bin/generate_alphabet_file.py` for generating alphabet file from directory where include valid CSV files
  - pass argument `--exclude_chars_rate` or `--exclude_chars_count` to exclude rare characters to down size your alphabet file
  - since the transcripts in SLR's mandarin dataset include some weird punctuation like `《`, `》` , the default script will also remove them.

### CODE REVIEW

**Comment by lissyx** [comment]
Thanks. I know nothing about those languages so I can't really review. But why the second script? We already have that feature in `bin/check_characters.py`

**Comment by mychiux413** [comment]
If we use `util/check_characters.py` with large mandarin datasets, might generate 6xxx ~ 7xxx alphabets.
But if we filter the rare characters like under 0.00001%, the alphabet size might surprisingly down to 4xxx around.
Because mandarin characters contain so many [variant characters](https://en.wikipedia.org/wiki/Variant_Chinese_character), they have SAME meaning, SAME pronunciation, but DIFFERENT character encoding, which might cause the model choose characters randomly from those variant alphabet, and then got worse loss/wer.

And since it's really hard to build a mandarin version's `unicodedata.normalize` tool, so the better strategy is:
1. To generate alphabet file excluded rare characters first
2. Use this tidy(?) alphabet file to filter those large mandarin datasets, drop those rows which contain rare characters.

**Comment by lissyx** [comment]
> If we use `util/check_characters.py` with large mandarin datasets, might generate 6xxx ~ 7xxx alphabets.

Why ?



> Because mandarin characters contain so many [variant characters](https://en.wikipedia.org/wiki/Variant_Chinese_character), they have SAME meaning, SAME pronunciation, but DIFFERENT character encoding,

Are we talking about different characters, or differents encoding for the same character ?



> And since it's really hard to build a mandarin version's `unicodedata.normalize` tool, so the better strategy is:

Still, I don't see how this justifies a separate file. Doing so will only generate noise with people using the wrong tool.

**Comment by lissyx** [comment]
>     * since the transcripts in SLR's mandarin dataset include some weird punctuation like `《`, `》` , the default script will also remove them.

This would likely be rather done on the importer side, not when generating the alphabet: your CSVs should not contain punctuation if you don't want some in the model.

You can't have an alphabet that does not contains all characters that appears in your dataset.

**Comment by mychiux413** [comment]
> > If we use `util/check_characters.py` with large mandarin datasets, might generate 6xxx ~ 7xxx alphabets.
> 
> Why ?
> 
> > Because mandarin characters contain so many [variant characters](https://en.wikipedia.org/wiki/Variant_Chinese_character), they have SAME meaning, SAME pronunciation, but DIFFERENT character encoding,
> 
> Are we talking about different characters, or differents encoding for the same character ?
> 
for example: '戶'(\xe6\x88\xb6) '戸'(\xe6\x88\xb8) in mandarin are the same pronunciation, same meaning, but in computer, they are different characters. Even in human cognition, we know that they have different representations, neither way of writing is wrong. but when these two characters appear in the same training file, it will be a nightmare.
> > And since it's really hard to build a mandarin version's `unicodedata.normalize` tool, so the better strategy is:
> 
> Still, I don't see how this justifies a separate file. Doing so will only generate noise with people using the wrong tool.
Yes, you are right, misuse can lead to more disasters, I'll remove this one.

**Comment by lissyx** [comment]
> for example: '戶'(\xe6\x88\xb6) '戸'(\xe6\x88\xb8) in mandarin are the same pronunciation, same meaning, but in computer, they are different characters. Even in human cognition, we know that they have different representations, neither way of writing is wrong. but when these two characters appear in the same training file, it will be a nightmare.

Ok, Wouldn't it be possible to normalize to one or the other character ? Instead of just dropping. Of course, this should be done before generating the alphabet, it should be done at importer-level maybe.

The rationale seems similar to something I recently fixed on Common Voice french dataset, although the issue was much easier to deal with: `NFCD` vs `NFKD`, e.g., for `é`.

**Comment by mychiux413** [comment]
> > for example: '戶'(\xe6\x88\xb6) '戸'(\xe6\x88\xb8) in mandarin are the same pronunciation, same meaning, but in computer, they are different characters. Even in human cognition, we know that they have different representations, neither way of writing is wrong. but when these two characters appear in the same training file, it will be a nightmare.
> 
> Ok, Wouldn't it be possible to normalize to one or the other character ? Instead of just dropping. Of course, this should be done before generating the alphabet, it should be done at importer-level maybe.
> 
> The rationale seems similar to something I recently fixed on Common Voice french dataset, although the issue was much easier to deal with: `NFCD` vs `NFKD`, e.g., for `é`.

If there is, it should be a large reference table for mandarin, but I can't find a standard normalization package, even the standard rules, because different regions have different consensus.

By the way, I happen to be clearing Common Voice English V2 dataset, I found many rows has different space style like:
`I 'm` `I'm`
`dog 's` `women's`

But I can't just use regular expression to clear them, like: `re.sub(r'\s\'', '\'', string)`, because it would convert `to 'super fun playground'` -> `to'super fun playground'`, (I also want to strip `'` out)

TED Release2 datasets also has this problem
LibriSpeech & voxforge are clean.

**Comment by lissyx** [comment]
> If there is, it should be a large reference table for mandarin, but I can't find a standard normalization package, even the standard rules, because different regions have different consensus.

Ok, and there's absolutely no generic rule accepted by mostly everyone ?

**Comment by mychiux413** [comment]
> > If there is, it should be a large reference table for mandarin, but I can't find a standard normalization package, even the standard rules, because different regions have different consensus.
> 
> Ok, and there's absolutely no generic rule accepted by mostly everyone ?

As far as I know, maybe `opencc` Is the most widely accepted normalization package.

the package `opencc` I used in `bin/convert_csv_zh_cn_to_zh_tw.py` can convert characters between different region(`zh-cn` `zh-hk` `zh-tw`), it said that the character reference table is generated after manual collation, and is also the most consistent with the regionality I have seen so far.
I sometimes use `opencc` to convert `zh-cn` dataset as `zh-cn` to achieve "normalization", but I'm not literature expert, and I can't iterate through all the characters, so I can't guarantee whether it will cause any harm to the datasets.

here is another example:
wiki says '戶' '户' '戸' are variant characters, in `zh-tw` is `戶`,  when I use `opencc`:
```
print('to tw: ', opencc.OpenCC('s2tw').convert('戶户戸'))
# to tw:  戶戶戸
```
as above, '戸' should be converted as '戶', but doen't work.

**Comment by irvin** [comment]
It's valid to reduce variant chars in Traditional Chinese texts by converting it as zh-cn to zh-tw with opencc, actually I [had also collected some variant chars](https://github.com/irvin/cc0-sentences/blob/master/zh-tw_char_variant.json) for my zh-tw cc0 corpus for Common Voice.  

But I'm also wondering if we should put this in DeepSpeech here. I don't find any scripts for other languages here. 
@lissyx Do we have a better place to collect the scripts for cleaning datasets?

**Comment by lissyx** [comment]
No, that's really a case for external tooling. At the same time, I have similar local patches for french.

I really think this might be splitted into a part, the normalization, that would go into common voice importer, and the second part, improving alphabet file generation from dataset.

**Comment by irvin** [comment]
Or could we find someplace for documenting all those self-made tools for normalizing the datasets? For example, in [Wiki](https://github.com/mozilla/DeepSpeech/wiki) and pointed from Readme.

Assuming every locale has some similar need, it's good to store info and links of all those tools for other people to re-use while fork and experimenting DeepSpeech.

**Comment by lissyx** [comment]
> Or could we find someplace for documenting all those self-made tools for normalizing the datasets? For example, in [Wiki](https://github.com/mozilla/DeepSpeech/wiki) and pointed from Readme.

In this case, it is specific to the dataset, so I think it would make sense to take care of that in `import_cv2.py`

@mychiux413 Can you split your changes amongst both files?

**Comment by reuben** [comment]
You can just run the standard `opencc` binary on a CSV file directly, there shouldn't be a need to write a Python wrapper for it. If your filenames have Mandarin characters in them, you can select just the transcript column using a tool like [XSV](https://github.com/BurntSushi/xsv):

```
$ cat example.csv
wav_filename,wav_filesize,transcript
foo.wav,1,中国

$ xsv select -- transcript example.csv | opencc -c s2t | xsv cat columns <(xsv select -- wav_filename,wav_filesize example.csv) - > example_traditional.csv

$ cat example_traditional.csv
wav_filename,wav_filesize,transcript
foo.wav,1,中國
```

**Comment by mychiux413** [comment]
I share this script because my personal requirement, I use it to manage different datasets.
With directory options: `--from_dir` `--to_dir`, it can easily convert a bunch of csv files (Ex: SLR57, aishell, aidatatang, ...) into another `zh-tw` directory, and keep the same filename like: train.csv, dev.csv, test.csv....
And additionally, because I don't know that there is XSV tool to select columns,
so, maybe we can close this PR.

**Comment by reuben** [comment]
I know the French community started their own repo to collect French specific code, scripts, configuration files so that they could collaborate and share efforts. Maybe something similar could be done for Mandarin? I think this is the repo: https://github.com/Common-Voice/commonvoice-fr @lissyx can confirm

**Comment by lissyx** [comment]
That's right

**Comment by irvin** [comment]
@reuben that would be great and I found that we already have one empty repo here, https://github.com/Common-Voice/mandarin
can you help me to get access to it, and I can start some documents and add some of my scripts inside?

**Comment by reuben** [comment]
@irvin sorry I completely missed your comment. I don't have access to the @Common-Voice org here. @mbransn is the one to talk to.

**Comment by mbransn** [comment]
@irvin it appears you already had write access to that repo? I've just made you a maintainer. Please let me know if you need further collaborators added. Thanks for the ping @reuben.

**Comment by lissyx** [comment]
>  so, maybe we can close this PR.

Since there has been no more activity from you on that @mychiux413, I'm closing. Feel free to open a new PR if you think there's value :)

**Pull request closed without merging**
