### PR TITLE
Support for microphone streaming in swift native client test project

### PR DESCRIPTION
**Pull request by erksch**
This adds support for microphone streaming to the Swift native client test project.

The audio is recorded via `AVCaptureSession` and converted from any input format to 16000Hz via the `AudioConverter` API.

I moved the code for recognizing an audio file together with the new code for recognizing microphone input into a new `DeepSpeech.swift`.

Because I did not want to commit my project file because of many unrelated changes, @reuben maybe you could commit a new proj file where `DeepSpeech.swift` and `AudioContext.swift` are included.

Because the file transcription did not work for me before this has to be tested. The microphone streaming works great and prints intermediate results and final result to the console. One could think of adding an event handler for results to DeepSpeech.swift so the ContentView can add a listener and display the results nicely.

The captured audio data is recorded and written into a `recording.pcm` file. As a note: not the original audio is saved, but the audio after conversion to 16000 Hz. The file can be easily opened with Adobe Audition for example. This way you can check for yourself that the capturing and conversion works. The file can be downloaded by downloading the app container from the device in the `Devices & Simulators` dialog in XCode.

### CODE REVIEW

**Comment by erksch** [comment]
Sorry I missed the author comment. I'll set you as the author for `AudioContext.swift` and you and me for `DeepSpeech.swift` if thats alright.

**Comment by reuben** [comment]
I just tried your code with a single file on my iPhone Xs and it works fine. Really puzzling why you can't get loading from a file to work.

```
TensorFlow: v2.2.0-17-g0854bb5188
DeepSpeech: v0.9.0-alpha.3-44-gcbf9a8d2
2020-07-27 20:17:35.424637+0200 deepspeech_ios_test[6563:3153221] Initialized TensorFlow Lite runtime.
/private/var/containers/Bundle/Application/3C928228-453E-4C3B-A88D-8213A6DF699F/deepspeech_ios_test.app/1284-134647-0003.wav
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 8192 samples
read 2832 samples
"/private/var/containers/Bundle/Application/3C928228-453E-4C3B-A88D-8213A6DF699F/deepspeech_ios_test.app/1284-134647-0003.wav": 3.344200015068054 - constantine easily believed that the heretics who presumed to dispute his opinions or to oppose his commands were guilty of the most absurd and criminal obstinacy and that a seasonable application of moderate severities might save those unhappy men from the danger of an everlasting condemnation
```

**Comment by reuben** [comment]
Opened #3191 to make sure it builds on CI.

**Comment by reuben** [comment]
Merged in #3191! Thanks a lot @erksch :D

**Comment by erksch** [comment]
Awesome! 
But one question, shouldn't be a demo like this be in the examples repo? Or is that more difficult because the library would need to be available as a dependency like via cocoapods?

**Comment by reuben** [comment]
Yeah, ideally we'd be available in Cocoapods or something like that, but also we use deepspeech_ios_test to make sure usage of the API builds in CI as well. Otherwise we may break stuff without noticing if we only build the binding itself.

**Pull request closed without merging**
