### PR TITLE
Fix for DS_IntermediateDecode modifying live prefixes in DecoderState

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
@eggonlea can you try this fix and verify if it fixes the bug you found?

**Comment by reuben** [comment]
Yes, it is. I'm trying to design a better way of fixing this, the PathTrie makes it a bit tricky.

**Comment by reuben** [comment]
Although it should only really matter if you call intermediate decode *very* often.

**Comment by reuben** [comment]
@lissyx the crux of the problem here is that in `decoder_decode` we were sorting the live prefixes still being used by `decoder_next`, which changes the behavior of the decoder over the whole stream. This solution is a bit hacky, it copies the prefix vector, stores the modified scores outside of the vector, and then sorts them with an external score, which keeps all the live prefixes unchanged except for `approx_ctc` (which isn't used in `decoder_next`). A better fix requires more substantial changes to the decoder implementation, but I'd rather fix this quickly for 0.5.1.

**Comment by lissyx** [comment]
r+

**Pull request merged**
