### PR TITLE
Revert repository to before decomposition PR

### PR DESCRIPTION
**Pull request by reuben**
Reverts commit 8f341cf2b77d7215314cc2f8c286562b6c60c93c, commit 2b513d06308e2805942e209332f07e28849c050c, commit b27cf0325009e0fb151c278b1cc856078b45206b, commit d8856a94c83a92cbba01d2ae4b4fd17a84cb520c, commit e39f7cfe2773e70aea65c9ec6309e574c839afc4, commit 06ad0d802677f5d8deca8dc24762167951f3050d, commit 2c832169de49e554000ba049c1d1c80f0795e5ea.

If this fixes the server crashes, then we need to reapply the changes that happened after the decomposition PR. @lissyx, this reverts #376, do we need to move some files around in the server before merging?

### CODE REVIEW

**Comment by reuben** [comment]
Note to self: reopen #376, #372, #368, #313 if/when this gets merged.

**Comment by kdavis-mozilla** [comment]
@reuben Before reviewing/merging, I'm going to run 10 epochs of this branch to try to re-produce the crash. If it crashes, we know the problem is not due to code in our repo but the server itself.

**Comment by lissyx** [comment]
@reuben data on the server should not be a big deal by themselves, we can symlink ~doyouunderstand/.local/share/deepspeech_wer/ to /data/deepspeech_wer/ and this will do the trick.

What I am more concerned about is the extra amount of work that is going to come from reverting and relanding this later.

**Comment by kdavis-mozilla** [comment]
I guess once the TF 1.0.0 run finishes without any problem occurring, we can close this.

**Comment by kdavis-mozilla** [comment]
@reuben I'm going to close this as it looks like TF 1.0.0 is working with the refactor

**Comment by reuben** [comment]
\o/

**Comment by tilmankamp** [comment]
yeah!

**Pull request closed without merging**
