### PR TITLE
enable dynamic batch size through --export_batch_size -1 (see #1923)

### PR DESCRIPTION
**Pull request by nicolaspanel**
Usage: `$ CUDA_VISIBLE_DEVICES="" python DeepSpeech.py --notrain --notest --export_dir /path/to/models/ --checkpoint_dir /path/to/checkpoints/ --n_steps -1 --export_batch_size -1`

from client side:
```
tf_logits = session.graph.get_tensor_by_name('import/logits:0')
tf_input_node = session.graph.get_tensor_by_name('import/input_node:0')
tf_input_lengths = session.graph.get_tensor_by_name('import/input_lengths:0')
logits = tf_session.run(tf_logits, feed_dict={
    tf_input_node: pad_to_dense(windows),
    tf_input_lengths: features_lengths,
})
```

### CODE REVIEW

**Comment by nicolaspanel** [comment]
@reuben as discussed [here](https://github.com/mozilla/DeepSpeech/issues/1923#issuecomment-468737499), I removed state related stuffs.

I still have a question though: is it still needed/possible to reset `LSTM`s internal state before evaluating a new batch ?

**Comment by nicolaspanel** [comment]
@reuben is it ok for you ?

**Comment by reuben** [comment]
Hi @nicolaspanel, sorry for the delay, I was out on vacation.

**Comment by reuben** [comment]
> I still have a question though: is it still needed/possible to reset `LSTM`s internal state before evaluating a new batch ?

It's not needed anymore, since in that case we don't specify the `initial_state`, TF's RNN implementation will start from zero on every call.

**Pull request merged**
